# -*- mode: ruby -*-
# vi: set ft=ruby :

vagrant_root = File.dirname(__FILE__)

# This is useful for my home setup with Mac laptops and Windows desktops
vm_memory = 13000
vm_cores  = 2
if Vagrant::Util::Platform.windows? then
  vm_memory = 32000
  vm_cores  = 4
end

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu-20.04"
  config.vm.box_url = "https://storage.googleapis.com/gitpod-vagrant-boxes/ubuntu-20.04.2021-11-14-1927.box"
  config.vm.provider :vmware_desktop

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = vm_memory
    v.vmx["numvcpus"] = vm_cores
  end

  # Reuse mac so the my local network reassigns the same IP
  config.vm.network "public_network", :mac=> "080027123456"
  config.vm.hostname  = "gitpod.vm"

  if File.exists?(vagrant_root + "/tls.crt") && \
     File.exists?(vagrant_root + "/tls.key") && \
     File.exists?(vagrant_root + "/root_ca.crt")
    config.vm.provision "file", source: vagrant_root + "/tls.crt", destination: "/home/vagrant/secrets/https-certificates/tls.crt"
    config.vm.provision "file", source: vagrant_root + "/tls.key", destination: "/home/vagrant/secrets/https-certificates/tls.key"
    config.vm.provision "file", source: vagrant_root + "/root_ca.crt", destination: "/home/vagrant/secrets/https-certificates/root_ca.crt"
  end

  config.vm.provision "file", source: vagrant_root + "/config.yaml", destination: "/home/vagrant/config.yaml"
  config.vm.provision "file", source: vagrant_root + "/install-gitpod.sh", destination: "/home/vagrant/install-gitpod.sh"
  config.vm.provision "shell", path: "setup.sh"

end
